export const generateTEI = (metadata, content, annotations, page, exportFull = true) => {
  // Helper to escape XML characters
  const escapeXML = (str) => {
    if (!str) return "";
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&apos;");
  };

  // Helper to construct the annotated text
  const renderAnnotatedText = () => {
    if (!content) return "";

    let output = content;
    // Sort annotations in reverse order to avoid index shifting
    const sorted = [...annotations].sort((a, b) => b.start - a.start);

    sorted.forEach(a => {
      // Build attributes string
      let attrString = "";
      if (a.attributes) {
        Object.entries(a.attributes).forEach(([key, value]) => {
          if (value) {
            attrString += ` ${key}="${escapeXML(value)}"`;
          }
        });
      }

      const tagged = `<${a.type}${attrString}>${escapeXML(a.text)}</${a.type}>`;
      output = output.slice(0, a.start) + tagged + output.slice(a.end);
    });

    // Wrap in paragraphs
    return output.split(/\n\s*\n/).map(p => `<p>${p}</p>`).join("\n      ");
  };

  // If the user uploaded a full, pre-existing TEI XML file, don't double wrap it, just export it straight!
  if (content && content.trim().startsWith("<?xml")) {
    if (!exportFull) {
      // If we only want the text, strip out the XML header and return just the body content
      const bodyMatch = content.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
      if (bodyMatch) {
        return bodyMatch[1].trim();
      }
    }
    return content;
  }

  if (!exportFull) {
    return `<div type="page" n="${escapeXML(page)}">\n  <pb n="${escapeXML(page)}"/>\n  ${renderAnnotatedText()}\n</div>`;
  }

  // Construct the full XML using the user's manual annotations from the app
  return `<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>${escapeXML(metadata?.title || 'Untitled TEI Document')}</title>
        <author>${escapeXML(metadata?.author || 'Unknown Author')}</author>
      </titleStmt>
      <publicationStmt>
        <p>Unpublished draft generated by TEI Editor.</p>
      </publicationStmt>
      <sourceDesc>
        <msDesc>
          <msIdentifier>
            <repository>Private Collection</repository>
          </msIdentifier>
          <msContents>
            <summary>${escapeXML(metadata?.sourceDesc || 'No description provided.')}</summary>
          </msContents>
        </msDesc>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <div type="page" n="${escapeXML(page)}">
        <pb n="${escapeXML(page)}"/>
        ${renderAnnotatedText()}
      </div>
    </body>
  </text>
</TEI>`;
};
